module.exports = {
  docs: [
    'introduction',
    'userInteraction',
    {
      type: 'category',
      label: 'Components customization',
      collapsed: false,
      items: ['componentsCustomization/node', 'componentsCustomization/port'],
    },
    'stateManagement',
    {
      type: 'category',
      label: 'Api',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api', // 'api' is the 'out' directory
        },
      ],
    },
  ],
};
